// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6.Models;

namespace Mission6.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20230221210539_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Action, Adventure, Drama"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Fantasy"
                        });
                });

            modelBuilder.Entity("Mission6.Models.MovieFormResponse", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationID");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            CategoryID = 1,
                            Director = "Peter Jackson",
                            Edited = false,
                            LentTo = "Nobody",
                            Notes = "Great movie!",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Year = "2001"
                        },
                        new
                        {
                            ApplicationID = 2,
                            CategoryID = 1,
                            Director = "Peter Jackson",
                            Edited = false,
                            LentTo = "Nobody",
                            Notes = "Has some great action scenes!",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Two Towers",
                            Year = "2002"
                        },
                        new
                        {
                            ApplicationID = 3,
                            CategoryID = 1,
                            Director = "Peter Jackson",
                            Edited = false,
                            LentTo = "Nobody",
                            Notes = "Words cannot describe how great this movie is!",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Return of the Ring",
                            Year = "2003"
                        });
                });

            modelBuilder.Entity("Mission6.Models.MovieFormResponse", b =>
                {
                    b.HasOne("Mission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
